<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDatastoreTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('datastore', function (Blueprint $table) {
			$table->bigIncrements('id');
            $table->string('type', 255)->nullable();
            $table->string('namespace', 255)->nullable();
            $table->string('module', 255);
            $table->string('name', 255)->nullable();
            $table->string('key', 255)->nullable();
            $table->unsignedTinyInteger('private')->nullable()->default(0);
            $table->longText('value')->nullable();
            $table->string('options', 255)->nullable();
            $table->string('meta', 255)->nullable();
            $table->string('accept', 255)->nullable()->comment('comma separated list of assets it accepts as related');
            $table->string('accept_limit', 255)->nullable();
            $table->unsignedBigInteger('datastore_id')->nullable();
            $table->string('shortname', 255)->nullable();
            $table->string('children', 255)->nullable();
            $table->unsignedTinyInteger('is_child')->nullable();
            $table->string('status', 255)->nullable();
            $table->string('embedded', 255)->nullable();
            $table->string('theme', 50)->nullable();
            $table->text('meta_description')->nullable();
            $table->text('meta_keywords')->nullable();
            $table->text('page_css')->nullable();
            $table->text('page_js')->nullable();
            $table->string('limit', 20)->nullable();
            $table->string('warning', 20)->nullable();
            $table->string('callback', 255)->nullable();
            $table->unsignedTinyInteger('required')->nullable();
            $table->string('comment_equals', 255)->nullable();
            $table->integer('max_instances')->nullable()->default(0);
            $table->date('start_date')->nullable();
            $table->date('end_date')->nullable();
			$table->string('lang', 255)->nullable();
			$table->timestamps();




            $table->index('datastore_id', 'index_foreignkey_datastore');

            $table->foreign('datastore_id', 'datastore_ibfk_1')->references('id')->on('datastore')->onDelete('CASCADE')->onUpdate('RESTRICT');

        });



    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('datastore');
    }
}
